---
title: "p8105_hw6_jt3098"
author: "Jieqi Tu (jt3098)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(questionr)
library(purrr)
```

## Problem 1

#### Data importing
```{r data importing for problem 1, message=FALSE}
# import data for problem 1
homicide_data = read_csv("./data/homicide-data.csv")
```

#### Data cleaning and manipulation
```{r creating and manipulating variables, message=FALSE}
# Make a "city_state" variable
homicide_data = 
  homicide_data %>%
  mutate(city_state = str_c(city, ", ", state)) %>%
  select(-city, -state)

# Make a binary variable to show whether this case is solved
# "0" means the case is unsolved yet, and "1" means the case is already solved
homicide_data = 
  homicide_data %>%
  mutate(case_status = ifelse(disposition == "Closed by arrest", 1, 0))

# Make sure that the "victim_age" is numeric
homicide_data = 
  homicide_data %>%
  mutate(victim_age = replace(victim_age, victim_age == "Unknown", ""),
         victim_age = as.numeric(victim_age))

# Convert "victim_sex" from character to factor
homicide_data$victim_sex = factor(homicide_data$victim_sex,
                                  levels = c("Male", "Female"))

# Omit several cities that do not have the correct information
homicide_data = 
  homicide_data %>%
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))

# Modify "victim_race" variable
homicide_data = 
  homicide_data %>%
  mutate(victim_race = ifelse(victim_race == "White", "white", "non-white"))

# Relevel "victim_race" variable
homicide_data$victim_race = factor(homicide_data$victim_race,
                                   levels = c("white", "non-white")) # Make "white" be the reference arm of all factors
```

#### Regression Analysis for Baltimore city
```{r Baltimore regression}
# Create a new dataframe that only contains data about Baltimore city
homicide_Baltimore =
  homicide_data %>%
  filter(city_state == "Baltimore, MD")

# Fit a glm regression for Baltimore
Baltimore_glm = glm(case_status ~ victim_age + victim_race + victim_sex, data = homicide_Baltimore, family = binomial)

# See the result of the glm regression
broom::tidy(Baltimore_glm) %>% knitr::kable()
```

```{r odds ratio, message=FALSE}
# Calculate the estimation and confidence interval of odds ratio
status_sex_glm = glm(case_status ~ victim_sex + victim_race + victim_age, data = homicide_Baltimore, family = binomial)
ci_oddsratio = odds.ratio(status_sex_glm, level = 0.95)
ci_oddsratio =
  ci_oddsratio %>%
  as.data.frame() %>%
  select(-p) %>%
  round(digits = 3)

ci_oddsratio %>% knitr::kable()
```

Comments: From the result, we could know that the OR estimate is 0.441 with the 95% CI: [0.312, 0.620], keeping all other variables fixed.

```{r odds ratio for each city}
# Make list columns to make glm results for each city
homicide_city_glm = 
  homicide_data %>%
  group_by(city_state) %>%
  nest() %>%
  mutate(regression = map(data, ~glm(case_status ~ victim_sex + victim_race + victim_age, data = homicide_data, family = binomial))) %>%
  select(-data) %>%
  unnest()
```

```{r unnest the result of glm}
# Unnest the glm result and select only the race term
homicide_city_glm = 
  homicide_city_glm %>%
  unnest() %>%
  filter(term == "victim_racenon-white")

# Calculate the confidence interval for each city
homicide_city_glm = 
  homicide_city_glm %>%
  mutate(ci_result = map())
```

### Problem 2

#### Data importing
```{r data importing for problem 2, message=FALSE}
# Import dataset for problem 2
birthweight_data = read_csv("./data/birthweight.csv")
```

```{r data cleaning and manipulation for birthweight data}
# Convert variable types from numeric to factor
birthweight_data$babysex = as.factor(birthweight_data$babysex)
birthweight_data$frace = as.factor(birthweight_data$frace)
birthweight_data$mrace = as.factor(birthweight_data$mrace)

# Check for NA values
n_NA = sapply(birthweight_data[1:20], function(x) sum(length(which(is.na(x)))))
n_NA %>% knitr::kable()
```

```{r model building for birthweight data}

```

