p8105\_hw6\_jt3098
================
Jieqi Tu (jt3098)

Problem 1
---------

#### Data importing

``` r
# import data for problem 1
homicide_data = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```

#### Data cleaning and manipulation

``` r
# Make a "city_state" variable
homicide_data = 
  homicide_data %>%
  mutate(city_state = str_c(city, ", ", state)) %>%
  select(-city, -state)

# Make a binary variable to show whether this case is solved
# "0" means the case is unsolved yet, and "1" means the case is already solved
homicide_data = 
  homicide_data %>%
  mutate(case_status = ifelse(disposition == "Closed by arrest", 1, 0))

# Make sure that the "victim_age" is numeric
homicide_data = 
  homicide_data %>%
  mutate(victim_age = as.numeric(victim_age))
```

    ## Warning in evalq(as.numeric(victim_age), <environment>): NAs introduced by
    ## coercion

``` r
# Omit several cities that do not have the correct information
homicide_data = 
  homicide_data %>%
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))

# Modify "victim_race" variable
homicide_data = 
  homicide_data %>%
  mutate(victim_race = ifelse(victim_race == "White", "white", "non-white"),
         victim_race = fct_relevel(victim_race, "white", "non-white")) 
```

#### Regression Analysis for Baltimore city

``` r
# Create a new dataframe that only contains data about Baltimore city
homicide_Baltimore =
  homicide_data %>%
  filter(city_state == "Baltimore, MD")

# Fit a glm regression for Baltimore
Baltimore_glm = glm(case_status ~ victim_age + victim_race + victim_sex, data = homicide_Baltimore, family = binomial)

# See the result of the glm regression
broom::tidy(Baltimore_glm) %>% knitr::kable()
```

| term                  |    estimate|  std.error|  statistic|    p.value|
|:----------------------|-----------:|----------:|----------:|----------:|
| (Intercept)           |   1.1860305|  0.2346173|   5.055170|  0.0000004|
| victim\_age           |  -0.0069900|  0.0032627|  -2.142423|  0.0321594|
| victim\_racenon-white |  -0.8195997|  0.1746156|  -4.693738|  0.0000027|
| victim\_sexMale       |  -0.8877869|  0.1360573|  -6.525097|  0.0000000|

``` r
# Calculate the estimation and confidence interval of odds ratio
status_sex_glm = glm(case_status ~ victim_sex + victim_race + victim_age, data = homicide_Baltimore, family = binomial)
ci_oddsratio = odds.ratio(status_sex_glm, level = 0.95)
ci_oddsratio =
  ci_oddsratio %>%
  as.data.frame() %>%
  select(-p) %>%
  round(digits = 3)

ci_oddsratio %>% knitr::kable()
```

|                       |     OR|  2.5 %|  97.5 %|
|-----------------------|------:|------:|-------:|
| (Intercept)           |  3.274|  2.076|   5.212|
| victim\_sexMale       |  0.412|  0.315|   0.537|
| victim\_racenon-white |  0.441|  0.312|   0.620|
| victim\_age           |  0.993|  0.987|   0.999|

Comments: From the result, we could know that the OR estimate is 0.441 with the 95% CI: \[0.312, 0.620\], keeping all other variables fixed.

``` r
# Make list columns to make glm results for each city
homicide_city_glm =
  homicide_data %>% 
  # first creating a listcolumn organized by city_state
  group_by(city_state) %>% 
  nest() %>% 
  # running glm on every city
  mutate(regression = map(data, ~glm(case_status ~ victim_sex + victim_race + victim_age, 
                                      family = binomial, data = .x)), 
         regression = map(regression, broom::tidy)) %>% 
  select(-data) 
```

``` r
# Unnest the glm result and select only the race term
homicide_city_glm =
  homicide_city_glm %>%
  unnest() %>%
  filter(term == "victim_racenon-white")

# Calculate the confidence interval for each city
homicide_city_glm = 
  homicide_city_glm %>%
  mutate(OR = exp(estimate),
         OR_lower = exp(estimate - 1.96 * std.error), 
         OR_upper = exp(estimate + 1.96 * std.error), 
         city_state = fct_reorder(city_state, estimate)) %>% 
  select(city_state, OR, OR_lower, OR_upper)
```

``` r
homicide_city_glm %>%
  ggplot(aes(x = city_state, y = OR)) + geom_point() +
  geom_errorbar(aes(ymin = OR_lower, ymax = OR_upper)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, size = 8)) +
  labs(
    title = "Odds Ratio and 95% Confidence Interval for Each City",
    x = "City, State",
    y = "Odds Ratio and 95% Confidence Interval"
  )
```

![](p8105_hw6_jt3098_files/figure-markdown_github/making%20a%20plot%20to%20show%20the%20ci%20for%20each%20city-1.png)

Comments: From the graph, we could see that, Boston has the lowest odds ratio, while Tempa has the highest odds ratio. It is also noticeable that Durham has the widest confidence interval range.

### Problem 2

#### Data importing

``` r
# Import dataset for problem 2
birthweight_data = read_csv("./data/birthweight.csv")
```

``` r
# Convert variable types from numeric to factor
birthweight_data$babysex = as.factor(birthweight_data$babysex)
birthweight_data$frace = as.factor(birthweight_data$frace)
birthweight_data$mrace = as.factor(birthweight_data$mrace)

# Check for NA values
n_NA = sapply(birthweight_data[1:20], function(x) sum(length(which(is.na(x)))))
n_NA %>% knitr::kable()
```

|          |    x|
|----------|----:|
| babysex  |    0|
| bhead    |    0|
| blength  |    0|
| bwt      |    0|
| delwt    |    0|
| fincome  |    0|
| frace    |    0|
| gaweeks  |    0|
| malform  |    0|
| menarche |    0|
| mheight  |    0|
| momage   |    0|
| mrace    |    0|
| parity   |    0|
| pnumlbw  |    0|
| pnumsga  |    0|
| ppbmi    |    0|
| ppwt     |    0|
| smoken   |    0|
| wtgain   |    0|

``` r
# Construct a multiple linear model with all predictors for birthweight
birthweight_lm_all = lm(bwt ~ ., data = birthweight_data)
summary(birthweight_lm_all) # Check the estimates and p-values for all predictors
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ ., data = birthweight_data)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1097.68  -184.86    -3.33   173.09  2344.15 
    ## 
    ## Coefficients: (3 not defined because of singularities)
    ##               Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) -6265.3914   660.4011  -9.487  < 2e-16 ***
    ## babysex2       28.7073     8.4652   3.391 0.000702 ***
    ## bhead         130.7781     3.4523  37.881  < 2e-16 ***
    ## blength        74.9536     2.0217  37.075  < 2e-16 ***
    ## delwt           4.1007     0.3948  10.386  < 2e-16 ***
    ## fincome         0.2898     0.1795   1.614 0.106551    
    ## frace2         14.3313    46.1501   0.311 0.756168    
    ## frace3         21.2361    69.2960   0.306 0.759273    
    ## frace4        -46.9962    44.6782  -1.052 0.292912    
    ## frace8          4.2969    74.0741   0.058 0.953745    
    ## gaweeks        11.5494     1.4654   7.882 4.06e-15 ***
    ## malform         9.7650    70.6259   0.138 0.890039    
    ## menarche       -3.5508     2.8951  -1.226 0.220083    
    ## mheight         9.7874    10.3116   0.949 0.342588    
    ## momage          0.7593     1.2221   0.621 0.534418    
    ## mrace2       -151.4354    46.0453  -3.289 0.001014 ** 
    ## mrace3        -91.3866    71.9190  -1.271 0.203908    
    ## mrace4        -56.4787    45.1369  -1.251 0.210901    
    ## parity         95.5411    40.4793   2.360 0.018307 *  
    ## pnumlbw             NA         NA      NA       NA    
    ## pnumsga             NA         NA      NA       NA    
    ## ppbmi           4.3538    14.8913   0.292 0.770017    
    ## ppwt           -3.4716     2.6121  -1.329 0.183913    
    ## smoken         -4.8544     0.5871  -8.269  < 2e-16 ***
    ## wtgain              NA         NA      NA       NA    
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 272.5 on 4320 degrees of freedom
    ## Multiple R-squared:  0.7183, Adjusted R-squared:  0.717 
    ## F-statistic: 524.6 on 21 and 4320 DF,  p-value: < 2.2e-16

``` r
# Use step-wise method to build a linear model with fewer predictors
step(birthweight_lm_all, direction = "backward")
```

    ## Start:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     pnumlbw + pnumsga + ppbmi + ppwt + smoken + wtgain
    ## 
    ## 
    ## Step:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     pnumlbw + pnumsga + ppbmi + ppwt + smoken
    ## 
    ## 
    ## Step:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     pnumlbw + ppbmi + ppwt + smoken
    ## 
    ## 
    ## Step:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     ppbmi + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - frace     4    124365 320848704 48712
    ## - malform   1      1419 320725757 48716
    ## - ppbmi     1      6346 320730684 48716
    ## - momage    1     28661 320752999 48716
    ## - mheight   1     66886 320791224 48717
    ## - menarche  1    111679 320836018 48717
    ## - ppwt      1    131132 320855470 48718
    ## <none>                  320724338 48718
    ## - fincome   1    193454 320917792 48718
    ## - parity    1    413584 321137922 48721
    ## - mrace     3    868321 321592659 48724
    ## - babysex   1    853796 321578134 48727
    ## - gaweeks   1   4611823 325336161 48778
    ## - smoken    1   5076393 325800732 48784
    ## - delwt     1   8008891 328733230 48823
    ## - blength   1 102050296 422774634 49915
    ## - bhead     1 106535716 427260054 49961
    ## 
    ## Step:  AIC=48711.51
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     ppbmi + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - malform   1      1447 320850151 48710
    ## - ppbmi     1      6975 320855679 48710
    ## - momage    1     28379 320877083 48710
    ## - mheight   1     69502 320918206 48710
    ## - menarche  1    115708 320964411 48711
    ## - ppwt      1    133961 320982665 48711
    ## <none>                  320848704 48712
    ## - fincome   1    194405 321043108 48712
    ## - parity    1    414687 321263390 48715
    ## - babysex   1    852133 321700837 48721
    ## - gaweeks   1   4625208 325473911 48772
    ## - smoken    1   5036389 325885093 48777
    ## - delwt     1   8013099 328861802 48817
    ## - mrace     3  13540415 334389119 48885
    ## - blength   1 101995688 422844392 49908
    ## - bhead     1 106662962 427511666 49956
    ## 
    ## Step:  AIC=48709.53
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     menarche + mheight + momage + mrace + parity + ppbmi + ppwt + 
    ##     smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - ppbmi     1      6928 320857079 48708
    ## - momage    1     28660 320878811 48708
    ## - mheight   1     69320 320919470 48708
    ## - menarche  1    116027 320966177 48709
    ## - ppwt      1    133894 320984044 48709
    ## <none>                  320850151 48710
    ## - fincome   1    193784 321043934 48710
    ## - parity    1    414482 321264633 48713
    ## - babysex   1    851279 321701430 48719
    ## - gaweeks   1   4624003 325474154 48770
    ## - smoken    1   5035195 325885346 48775
    ## - delwt     1   8029079 328879230 48815
    ## - mrace     3  13553320 334403471 48883
    ## - blength   1 102009225 422859375 49906
    ## - bhead     1 106675331 427525481 49954
    ## 
    ## Step:  AIC=48707.63
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     menarche + mheight + momage + mrace + parity + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - momage    1     29211 320886290 48706
    ## - menarche  1    117635 320974714 48707
    ## <none>                  320857079 48708
    ## - fincome   1    195199 321052278 48708
    ## - parity    1    412984 321270064 48711
    ## - babysex   1    850020 321707099 48717
    ## - mheight   1   1078673 321935752 48720
    ## - ppwt      1   2934023 323791103 48745
    ## - gaweeks   1   4621504 325478583 48768
    ## - smoken    1   5039368 325896447 48773
    ## - delwt     1   8024939 328882018 48813
    ## - mrace     3  13551444 334408523 48881
    ## - blength   1 102018559 422875638 49904
    ## - bhead     1 106821342 427678421 49953
    ## 
    ## Step:  AIC=48706.02
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     menarche + mheight + mrace + parity + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - menarche  1    100121 320986412 48705
    ## <none>                  320886290 48706
    ## - fincome   1    240800 321127090 48707
    ## - parity    1    431433 321317724 48710
    ## - babysex   1    841278 321727568 48715
    ## - mheight   1   1076739 321963029 48719
    ## - ppwt      1   2913653 323799943 48743
    ## - gaweeks   1   4676469 325562760 48767
    ## - smoken    1   5045104 325931394 48772
    ## - delwt     1   8000672 328886962 48811
    ## - mrace     3  14667730 335554021 48894
    ## - blength   1 101990556 422876847 49902
    ## - bhead     1 106864308 427750598 49952
    ## 
    ## Step:  AIC=48705.38
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     mheight + mrace + parity + ppwt + smoken
    ## 
    ##           Df Sum of Sq       RSS   AIC
    ## <none>                 320986412 48705
    ## - fincome  1    245637 321232048 48707
    ## - parity   1    422770 321409181 48709
    ## - babysex  1    846134 321832545 48715
    ## - mheight  1   1012240 321998651 48717
    ## - ppwt     1   2907049 323893461 48743
    ## - gaweeks  1   4662501 325648912 48766
    ## - smoken   1   5073849 326060260 48771
    ## - delwt    1   8137459 329123871 48812
    ## - mrace    3  14683609 335670021 48894
    ## - blength  1 102191779 423178191 49903
    ## - bhead    1 106779754 427766166 49950

    ## 
    ## Call:
    ## lm(formula = bwt ~ babysex + bhead + blength + delwt + fincome + 
    ##     gaweeks + mheight + mrace + parity + ppwt + smoken, data = birthweight_data)
    ## 
    ## Coefficients:
    ## (Intercept)     babysex2        bhead      blength        delwt  
    ##   -6098.822       28.558      130.777       74.947        4.107  
    ##     fincome      gaweeks      mheight       mrace2       mrace3  
    ##       0.318       11.592        6.594     -138.792      -74.887  
    ##      mrace4       parity         ppwt       smoken  
    ##    -100.678       96.305       -2.676       -4.843
